export default {
    path:"/shopManage",
    name:"shopManage",
    component:_=>import('@pages/shop-manage'),
    children:[
        {
            path:"businessList",
            name:"business-list",
            component:_=>import("@pages/shop-manage/business-list"),
            meta:{
                breadcrumb:[
                    {
                        path:"/shopManage",
                        text:"商品管理"  
                    },
                    {
                        path:"/shopManage/businessList",
                        text:"商家列表"  
                    }
                ]
            }
        },
        {
            path:"businessManage",
            name:"business-manage",
            component:_=>import("@pages/shop-manage/business-manage"),
            meta:{
                breadcrumb:[
                    {
                        path:"/shopManage",
                        text:"商品管理"  
                    },
                    {
                        path:"/shopManage/businessManage",
                        text:"商家管理"  
                    }
                ]
            }
        },
        {
            path:"orderList",
            name:"order-list",
            component:_=>import("@pages/shop-manage/order-list"),
            meta:{
                breadcrumb:[
                    {
                        path:"/shopManage",
                        text:"商品管理"  
                    },
                    {
                        path:"/shopManage/orderList",
                        text:"订单列表"  
                    }
                ]
            }
        }
    ]
}